### ISSUE TITLE
[FEATURE]: Install Sketch on CI to open generated Sketch files.

### ISSUE THREAD

**Issue by lukasholzer** [Dynatrace/sketchmine#9]
**Description**
We need Sketch installed on the CI (Azure Pipelines) to open the generated Sketch files and check if the generated file can be consumed by Sketch. (Somehow an end2end testing environment).

**Describe the solution you'd like 🚀**
When the library is generated (or a webpage) – Sketch has to open the file on the ci and check if everything is alright. (Test fixture file that should be generated, that tests all the features of Sketch).

Testing the Kraken validation Plugin would be a nice step in the future as well so think about it when implementing the test environment.

**Additional context**

Sample Travis configuration to install Sketch on the CI.

```yml
os: osx
language: node_js
cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
notifications:
  email: false
node_js:
  - 'lts/*'
before_install:
  - brew update
  - brew cask install sketch # install Sketch
  - mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3/Plugins" # create plugins folder
  - echo $SKETCH_LICENSE > "~/Library/Application Support/com.bohemiancoding.sketch3/.deployment" # add the Sketch license
  - nvm install-latest-npm
before_script:
  - npm prune
script:
  - npm run check
  # - npm run test:e2e -- --app=/Applications/Sketch.app
after_script:
  - rm "~/Library/App Support/com.bohemiancoding.sketch3/.deployment" # remove the Sketch license
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
InVision

```
